services:

  server:

     build: server/
     command: python ./server.py
     ports:
       - 1234:1234
  client:

     build: client/
     command: python ./client.py
     depends_on:
       - server
