---
services:
 web_nginx:
  image: nginx
  hostname: web_nginx
  container_name: web_nginx
  restart: unless-stopped
  environment:
   TZ: "Asia/Tomsk"
  ports:
   - 80:80
   - 443:443
  volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   - ./nginx/ssl:/etc/nginx/ssl
   - ./www_data:/usr/share/nginx/html
 web_php:
  build:
   context: ./php/
   args:
    buildno: 2023101101
  hostname: web_php
  container_name: web_php
  restart: unless-stopped
  user: root
  environment:
   TZ: "Asia/Tomsk"
  volumes:
   - ./www_data:/var/www/html
   - ./php/php.ini:/usr/local/etc/php/php.ini
 web_db:
  image: mariadb
  hostname: web_db
  container_name: web_db
  restart: unless-stopped
  environment:
   TZ: "Asia/Tomsk"
   MARIADB_DATABASE: docker_db
   MARIADB_USER: docker_db_user
   MARIADB_PASSWORD: docker_db_password
   MARIADB_ROOT_PASSWORD: root_password
  volumes:
   - ./mysql_data:/var/lib/mysql
 web_pma:
  image: phpmyadmin
  hostname: web_pma
  container_name: web_pma
  restart: unless-stopped
  environment:
   TZ: "Asia/Tomsk"
   PMA_HOST: web_db
   UPLOAD_LIMIT: 50M
  ports:
   - 81:80
